project_id = "nlghofpnwvmcevnmsiuj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_anonymous_sign_ins = false
enable_signup = true
enable_email_confirmations = false

[functions.whatsapp-notification]
verify_jwt = false

[functions.generate-ai-summary]
verify_jwt = false

[functions.generate-detailed-report]
verify_jwt = false

[functions.whatsapp-query-handler]
verify_jwt = false

[functions.loan-reminder-scheduler]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false