// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlghofpnwvmcevnmsiuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ2hvZnBud3ZtY2V2bm1zaXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzM2NTcsImV4cCI6MjA2OTA0OTY1N30.btZ1D-MJT2c2GKCrJb7oKV5KDZVC-H6IrwWxFBlfbkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});